kind: pipeline
name: default

steps:
- name: hi
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc --version

- name: basic_types
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc 01_basic_types/main.ts
  - node 01_basic_types/main.js

- name: variable_declarations
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc 02_variable_declarations/main.ts
  - node 02_variable_declarations/main.js

- name: interfaces
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc 03_interfaces/main.ts
  - node 03_interfaces/main.js

- name: classes
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc -t ES5 04_classes/*.ts
  - node 04_classes/main.js
