kind: pipeline
name: default

steps:
- name: hi
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc --version

- name: basic_types
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc 01_basic_types/main.ts
  - node 01_basic_types/main.js

- name: variable_declarations
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc 02_variable_declarations/main.ts
  - node 02_variable_declarations/main.js

- name: interfaces
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc 03_interfaces/main.ts
  - node 03_interfaces/main.js

- name: classes
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc -t ES5 04_classes/main.ts
  - node 04_classes/main.js

- name: functions
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc 05_functions/main.ts
  - node 05_functions/main.js

- name: generics
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc 06_generics/main.ts
  - node 06_generics/main.js

- name: enums
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc 07_enums/main.ts
  - node 07_enums/main.js

- name: type_inference
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc 08_type_inference/main.ts
  - node 08_type_inference/main.js

- name: type_compatibility
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc 09_type_compatibility/main.ts
  - node 09_type_compatibility/main.js

- name: advanced_types
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc 10_advanced_types/main.ts
  - node 10_advanced_types/main.js

- name: symbols
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc --lib "ES2020","DOM" 11_symbols/main.ts
  - node 11_symbols/main.js

- name: iterators_and_generators
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc --lib "ES2020","DOM" --downlevelIteration true 12_iterators_and_generators/main.ts
  - node 12_iterators_and_generators/main.js

- name: modules
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc 13_modules/main.ts
  - node 13_modules/main.js

- name: namespaces
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc --outfile 14_namespaces/main.js 14_namespaces/main.ts
  - node 14_namespaces/main.js

- name: namespaces_and_modules
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc 15_namespaces_and_modules/main.ts
  - node 15_namespaces_and_modules/main.js

- name: module_resolution
  image: node:12.18.0-slim
  commands:
  - echo "Module Resolution"

- name: declaration_merging
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc 17_declaration_merging/main.ts
  - node 17_declaration_merging/main.js

- name: jsx
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - npm install -g --save react react-dom
  - npm install -g --save-dev @types/react @types/react-dom
  - tsc --jsx react 18_jsx/main.tsx

- name: decorators
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - npm install -g --save reflect-metadata
  - tsc --target ES5 --experimentalDecorators --lib es2015,DOM 19_decorators/main.ts
  - node 19_decorators/main.js

- name: mixins
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc 20_mixins/main.ts

- name: triple_slash_directives
  image: node:12.18.0-slim
  commands:
  - echo "Triple Slash Directives"

- name: type_checking_javascript_files
  image: node:12.18.0-slim
  commands:
  - echo "Type Checking Javascript Files"

- name: utility_types
  image: node:12.18.0-slim
  commands:
  - npm install -g typescript
  - tsc --strictFunctionTypes true 23_utility_types/main.ts
  - node 23_utility_types/main.js
